



# ===============================
# = DATA SOURCE
# ===============================

facebook:
  client:
    clientId: 123944878277263
    clientSecret: 48fa009039ac57977fa61c10aef1f7d2
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

#security:
#  oauth2:
#    client:
#      clientId: 123944878277263
#      clientSecret: 48fa009039ac57977fa61c10aef1f7d2
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: DEBUG


spring:
  datasource:
      url: jdbc:mysql://localhost:3306/dbtrexapp
      username: root
      password: vertical601
      dbcp2:
        test-while-idle: true
        validation-query: SELECT 1
      tomcat:
        test-while-idle: true
        validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect



#spring.datasource.url =
#spring.datasource.username = root
#spring.datasource.password = vertical601
#spring.datasource.testWhileIdle = true
#spring.datasource.validationQuery = SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Thymeleaf configurations
# ===============================
#spring.thymeleaf.mode=LEGACYHTML5
#spring.thymeleaf.cache=false
#spring.mvc.dispatch-options-request=true

# ==============================================================
# = Spring Security / Queries for AuthenticationManagerBuilder
# ==============================================================
#spring.queries.users-query=select email, password, active from user where email=?
#spring.queries.roles-query=select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?

# ==============================================================
# = Spring Security
# ==============================================================

